### ISSUE TITLE
GUIDE: How to use news plus with FreshRSS secured behind cloudflare access

### ISSUE THREAD

**Issue by milindpatel63** [noinnion/newsplus#114]
For that 1 other guy like me who has exposed his freshRSS instance publically via cloudflare tunnel and secured it using cloudflare access.
If you want to use that with news+ and google reader extension,

Create a service token for your cloudflare access
Go to google reader extension source code files and open it in android studio.
Modify GoogleReaderClient activity
add following line of code at line no. 175 just after post.setHeader

		//cloudflare access service token
		post.setHeader("CF-Access-Client-Id", "yourclientid");
		post.setHeader("CF-Access-Client-Secret", "yoursecret");

also at line no. 227 just after get.setHeader

		//cloudflare access service token
		get.setHeader("CF-Access-Client-Id", "yourclientid");
		get.setHeader("CF-Access-Client-Secret", "yoursecret");

And, compile and install the apk on your device. (Y)

**Comment by Alkarex** [comment]
I am not using Cloudflare myself, but maybe some other FreshRSS users could be interested, so if you ever publish your fork, let us know (especially if you make a config / option to set extra headers in a generic way)
